// <auto-generated />
using DemolitionFalcons.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DemolitionFalcons.Data.Migrations
{
    [DbContext(typeof(DemolitionFalconsDbContext))]
    [Migration("20171217235934_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DemolitionFalcons.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Armour");

                    b.Property<int?>("GameId");

                    b.Property<int>("Hp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(12);

                    b.Property<int?>("PlayerId");

                    b.Property<int>("X");

                    b.Property<int>("Y");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("DemolitionFalcons.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Money");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<TimeSpan?>("Time");

                    b.Property<int?>("WinnerId");

                    b.Property<int>("Xp");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("DemolitionFalcons.Models.GameCharacter", b =>
                {
                    b.Property<int>("GameId");

                    b.Property<int>("CharacterId");

                    b.HasKey("GameId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("GameCharacters");
                });

            modelBuilder.Entity("DemolitionFalcons.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GamesPlayed");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<int>("Wins");

                    b.HasKey("Id");

                    b.HasAlternateKey("Username");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("DemolitionFalcons.Models.PlayerWeapon", b =>
                {
                    b.Property<int>("PlayerId");

                    b.Property<int>("WeaponId");

                    b.HasKey("PlayerId", "WeaponId");

                    b.HasIndex("WeaponId");

                    b.ToTable("PlayerWeapons");
                });

            modelBuilder.Entity("DemolitionFalcons.Models.Weapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ClipSize");

                    b.Property<int>("Damage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<int>("TotalCapacity");

                    b.HasKey("Id");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("DemolitionFalcons.Models.Character", b =>
                {
                    b.HasOne("DemolitionFalcons.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId");

                    b.HasOne("DemolitionFalcons.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");
                });

            modelBuilder.Entity("DemolitionFalcons.Models.GameCharacter", b =>
                {
                    b.HasOne("DemolitionFalcons.Models.Character", "Character")
                        .WithMany("Games")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DemolitionFalcons.Models.Game", "Game")
                        .WithMany("Characters")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DemolitionFalcons.Models.PlayerWeapon", b =>
                {
                    b.HasOne("DemolitionFalcons.Models.Player", "Player")
                        .WithMany("Weapons")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DemolitionFalcons.Models.Weapon", "Weapon")
                        .WithMany("Players")
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
